version: "3"

services:
  pmd:
    image: wrapper/pmd
    build:
      context: ./..
      dockerfile: ./apps/pmd/Dockerfile
    environment:
      PORT: 8090
    ports:
      - "8090:8090"
  eslint:
    image: wrapper/eslint
    build:
      context: ./..
      dockerfile: ./apps/eslint/Dockerfile
    environment:
      PORT: 8091
    ports:
      - "8091:8091"
  checkstyle:
    image: wrapper/checkstyle
    build:
      context: ./..
      dockerfile: ./apps/checkstyle/Dockerfile
    environment:
      PORT: 8092
    ports:
      - "8092:8092"
